import { CategoryData } from "@/Kiosk/types/types";

export const IMG = {
  catLivingRoom: "/images/Living-Room.avif",
  catDiningRoom: "/images/Dining-Room.avif",
  catKitchen:    "/images/Kitchen.avif",
  catBedroom:    "/images/Bed-Room.avif",
  catAppliances: "/images/Appliances.jpg",
  catBathroom:   "/images/Bathroom.avif",
  subSofas:      "/images/sub-product/sofas-fu003.avif",
  subSofaBeds:   "/images/sub-product/sofa-beds-10663.avif",
  subCabinets:   "/images/sub-product/cabinets-cupboards-st003.avif",
  subArmchair:   "/images/sub-product/armchairs.avif",
  subBookcase:   "/images/sub-product/bookcases.avif",
  subCarpets:    "/images/sub-product/rugs.avif",
  subShelves:    "/images/sub-product/shelving.avif",
  subSideTable:  "/images/sub-product/side-tables.avif",
  subCushions:   "/images/sub-product/cushions.avif",
  prod1a: "/images/product/glostad.jpg",
  prod1b: "/images/prod-glostad-2.jpg",
  prod1c: "/images/prod-glostad-3.jpg",
  prod1d: "/images/prod-glostad-dim.jpg",
  prod2a: "/images/product/klippan.jpg",
  prod3a: "/images/product/vimle.jpg",
};

export const CATEGORIES: CategoryData[] = [
  {
    id: "living-room",
    label: "LIVING ROOM",
    image: IMG.catLivingRoom,
    description: "Welcome to the living room category! Discover our wide selection of furniture and décor to transform your living space into a comfortable and stylish haven.",
    subCategories: [
      { id: "sofas",      label: "Sofas",      image: IMG.subSofas,     column: 0, row: 0 },
      { id: "sofa-beds",  label: "Sofa Beds",  image: IMG.subSofaBeds,  column: 1, row: 0 },
      { id: "cabinets",   label: "Cabinets",   image: IMG.subCabinets,  column: 2, row: 0 },
      { id: "armchair",   label: "Armchair",   image: IMG.subArmchair,  column: 0, row: 1 },
      { id: "bookcase",   label: "Bookcase",   image: IMG.subBookcase,  column: 1, row: 1 },
      { id: "carpets",    label: "Carpets",    image: IMG.subCarpets,   column: 2, row: 1 },
      { id: "shelves",    label: "Shelves",    image: IMG.subShelves,   column: 0, row: 2 },
      { id: "side-table", label: "Side Table", image: IMG.subSideTable, column: 1, row: 2 },
      { id: "cushions",   label: "Cushions",   image: IMG.subCushions,  column: 2, row: 2 },
    ],
    subCategoryTabs: [
      "Two-seat fabric sofas",
      "Three-seat fabric sofas",
      "Fabric sofas and chaise longues",
      "Corner sofas",
      "Modular sofas",
    ],
    products: {
      sofas: [
        {
          id: "glostad",
          name: "GLOSTAD",
          subtitle: "Loveseat, Knisa dark gray",
          price: 5999,
          stock: 12,
          sku: "G0008-12345",
          rating: 4,
          reviewCount: 240,
          isBestSeller: true,
          images: [IMG.prod1a, IMG.prod1b, IMG.prod1c, IMG.prod1d],
          colorVariants: [
            { label: "Dark Gray", image: IMG.prod1a },
            { label: "Blue",      image: IMG.prod1b },
          ],
          tags: ["Make more affordable"],
        },
        {
          id: "klippan",
          name: "KLIPPAN",
          subtitle: "Loveseat, Vissle gray",
          price: 11999,
          stock: 8,
          sku: "K0012-67890",
          rating: 4,
          reviewCount: 180,
          images: [IMG.prod2a],
          colorVariants: [{ label: "Gray", image: IMG.prod2a }],
        },
        {
          id: "vimle",
          name: "VIMLE",
          subtitle: "Loveseat, with wide armrests/Gunnared beige",
          price: 31999,
          stock: 5,
          sku: "V0034-11111",
          rating: 5,
          reviewCount: 95,
          images: [IMG.prod3a],
          colorVariants: [{ label: "Beige", image: IMG.prod3a }],
        },
      ],
    },
  },
  { id: "dining-room", label: "DINING ROOM", image: IMG.catDiningRoom, description: "Find the perfect dining set for memorable family meals and gatherings.", subCategories: [], subCategoryTabs: [], products: {} },
  { id: "kitchen",     label: "KITCHEN",     image: IMG.catKitchen,    description: "Organize and beautify your kitchen with our smart storage and accessories.", subCategories: [], subCategoryTabs: [], products: {} },
  { id: "bedroom",     label: "BED ROOM",    image: IMG.catBedroom,    description: "Create your dream bedroom with our beds, linens, and bedroom furniture.", subCategories: [], subCategoryTabs: [], products: {} },
  { id: "appliances",  label: "APPLIANCES",  image: IMG.catAppliances, description: "Modern home appliances to make everyday living easier and smarter.", subCategories: [], subCategoryTabs: [], products: {} },
  { id: "bathroom",    label: "BATH ROOM",   image: IMG.catBathroom,   description: "Transform your bathroom into a relaxing sanctuary.", subCategories: [], subCategoryTabs: [], products: {} },
];

export const HOME_CATEGORIES = CATEGORIES.map((c, i) => ({
  id: c.id,
  label: c.label,
  image: c.image,
  column: (i % 2) as 0 | 1,
  row: Math.floor(i / 2),
}));
